#!/bin/bash
# Reading hex color codes from url one code at a time.
while read -r hex;
do
    # Save RGP values as desimals to variables.
    r=$((0x${hex:0:2}));
    g=$((0x${hex:2:4}));
    b=$((0x${hex:4:6}));
    # If color is mostly red then it is shade of red, so print it.
    if [[ $r -gt $g+$b ]]
    then
        echo $hex;
    fi
done <<< $(curl https://webshell2017.picoctf.com/static/19de212231cdca44105cf871aabc9746/codes.txt -s | egrep -o "[0-9a-fA-F]{6}\b")